/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  integration: 'project-findtheproduct-4EzKjgJRWT403ipAQJ-sUYelfZZDG3wO',
  version: '2020-11-20',
};

export default ebconfig;
